import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const { Pool } = pg;

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

export async function seedQuiz(): Promise<void> {
  await prisma.quizQuestion.createMany({
        data: [
        {
            question: "Botol plastik termasuk jenis sampah apa?",
            optionA: "Organik",
            optionB: "Plastik",
            optionC: "Kaca",
            optionD: "Logam",
            correctAnswer: "B",
            points: 10,
        },
        {
            question: "Kertas bekas termasuk kategori sampah apa?",
            optionA: "Kertas",
            optionB: "Plastik",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "A",
            points: 8,
        },
        {
            question: "Kulit buah termasuk jenis sampah apa?",
            optionA: "Plastik",
            optionB: "Kaca",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "C",
            points: 5,
        },
        {
            question: "Kaleng minuman termasuk jenis sampah apa?",
            optionA: "Kaca",
            optionB: "Logam",
            optionC: "Organik",
            optionD: "Kertas",
            correctAnswer: "B",
            points: 12,
        },
        {
            question: "Botol kaca termasuk kategori apa?",
            optionA: "Plastik",
            optionB: "Kaca",
            optionC: "Logam",
            optionD: "Organik",
            correctAnswer: "B",
            points: 10,
        },
        {
            question: "Sisa makanan termasuk jenis sampah apa?",
            optionA: "Organik",
            optionB: "Plastik",
            optionC: "Kertas",
            optionD: "Logam",
            correctAnswer: "A",
            points: 5,
        },
        {
            question: "Kardus bekas termasuk jenis apa?",
            optionA: "Kertas",
            optionB: "Plastik",
            optionC: "Logam",
            optionD: "Organik",
            correctAnswer: "A",
            points: 8,
        },
        {
            question: "Sedotan plastik termasuk kategori apa?",
            optionA: "Kaca",
            optionB: "Plastik",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "B",
            points: 10,
        },
        {
            question: "Daun kering termasuk jenis sampah apa?",
            optionA: "Organik",
            optionB: "Plastik",
            optionC: "Kaca",
            optionD: "Logam",
            correctAnswer: "A",
            points: 5,
        },
        {
            question: "Majalah bekas termasuk jenis sampah apa?",
            optionA: "Kertas",
            optionB: "Plastik",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "A",
            points: 8,
        },
        {
            question: "Botol shampoo kosong termasuk jenis apa?",
            optionA: "Organik",
            optionB: "Plastik",
            optionC: "Kaca",
            optionD: "Logam",
            correctAnswer: "B",
            points: 10,
        },
        {
            question: "Pecahan kaca termasuk kategori apa?",
            optionA: "Plastik",
            optionB: "Logam",
            optionC: "Kaca",
            optionD: "Organik",
            correctAnswer: "C",
            points: 10,
        },
        {
            question: "Sendok plastik termasuk jenis apa?",
            optionA: "Plastik",
            optionB: "Logam",
            optionC: "Organik",
            optionD: "Kertas",
            correctAnswer: "A",
            points: 10,
        },
        {
            question: "Aluminium foil termasuk jenis apa?",
            optionA: "Kertas",
            optionB: "Logam",
            optionC: "Plastik",
            optionD: "Organik",
            correctAnswer: "B",
            points: 12,
        },
        {
            question: "Tisu bekas termasuk jenis apa?",
            optionA: "Kertas",
            optionB: "Organik",
            optionC: "Plastik",
            optionD: "Logam",
            correctAnswer: "B",
            points: 6,
        },
        {
            question: "Kotak pizza berminyak termasuk apa?",
            optionA: "Kertas",
            optionB: "Organik",
            optionC: "Plastik",
            optionD: "Logam",
            correctAnswer: "B",
            points: 7,
        },
        {
            question: "Botol air mineral kosong termasuk?",
            optionA: "Kaca",
            optionB: "Plastik",
            optionC: "Logam",
            optionD: "Organik",
            correctAnswer: "B",
            points: 10,
        },
        {
            question: "Koran bekas termasuk jenis apa?",
            optionA: "Kertas",
            optionB: "Plastik",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "A",
            points: 8,
        },
        {
            question: "Kaleng susu termasuk kategori apa?",
            optionA: "Plastik",
            optionB: "Logam",
            optionC: "Kaca",
            optionD: "Organik",
            correctAnswer: "B",
            points: 12,
        },
        {
            question: "Kulit telur termasuk jenis apa?",
            optionA: "Organik",
            optionB: "Kaca",
            optionC: "Plastik",
            optionD: "Logam",
            correctAnswer: "A",
            points: 5,
        },
        {
            question: "Bungkus snack plastik termasuk?",
            optionA: "Plastik",
            optionB: "Kertas",
            optionC: "Organik",
            optionD: "Logam",
            correctAnswer: "A",
            points: 10,
        },
        {
            question: "Botol parfum kaca termasuk?",
            optionA: "Kaca",
            optionB: "Plastik",
            optionC: "Logam",
            optionD: "Organik",
            correctAnswer: "A",
            points: 10,
        },
        {
            question: "Daun pisang bekas termasuk?",
            optionA: "Organik",
            optionB: "Plastik",
            optionC: "Kertas",
            optionD: "Logam",
            correctAnswer: "A",
            points: 5,
        },
        {
            question: "Kabel listrik bekas termasuk?",
            optionA: "Plastik",
            optionB: "Logam",
            optionC: "Organik",
            optionD: "Kertas",
            correctAnswer: "B",
            points: 12,
        },
        {
            question: "Kemasan susu karton termasuk?",
            optionA: "Kertas",
            optionB: "Plastik",
            optionC: "Logam",
            optionD: "Organik",
            correctAnswer: "A",
            points: 8,
        }
        ]
  });

  console.log("✅ Quiz seeded");
}   