import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getServerSession } from "next-auth";
import { SettingsProvider } from "@/components/providers/SettingsProvider";
import { SessionProvider } from "@/components/providers/SessionProvider";
import ThemeBootScript from "@/components/providers/ThemeBootScript";
import { Toaster } from "@/components/ui/sonner";
import { authOptions } from "@/lib/auth";
import { getGlobalSettingsForSession } from "@/lib/settings/server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const initialSettings = await getGlobalSettingsForSession(session);
  const themeClass =
    initialSettings.preferences.theme === "dark" ? " dark" : "";

  return (
    <html
      lang={initialSettings.preferences.language}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased${themeClass}`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeBootScript theme={initialSettings.preferences.theme} />
        <SessionProvider session={session}>
          <SettingsProvider initialSettings={initialSettings}>
            {children}
          </SettingsProvider>
        </SessionProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
